AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/*
    - config/initializers/*
    - config/application.rb
    - spec/teaspoon_env.rb
    - Rakefile
    - Gemfile

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Rails/HasAndBelongsToMany:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 80
