AllCops:
  Excludes:
    - db/schema.rb
    - db/migrate/*
    - bin/*
    - Gemfile
  RailsEnabled: true

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Rails/HasAndBelongsToMany:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 100
